name: Build LeafSDTools and release new version

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        os: [linux, macOS, windows]

    steps:
      - uses: actions/checkout@v6 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@v6 # v6.1.0
        with:
          go-version: "stable"

      - name: Build [macOS]
        if: matrix.os == 'macOS'
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -trimpath -o leafsdtools-companion main.go
          zip -9q LeafSDTools-Companion-$os-amd64.zip leafsdtools-companion LICENSE
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -trimpath -o leafsdtools-companion main.go
          zip -9q LeafSDTools-Companion-$os-arm64.zip leafsdtools-companion LICENSE
          rm leafsdtools-companion
          printf "sha256: %s\n" "$(shasum -a 256 LeafSDTools-Companion-$os-amd64.zip)"
          printf "sha256: %s\n" "$(shasum -a 256 LeafSDTools-Companion-$os-arm64.zip)"

      - name: Build [windows]
        if: matrix.os == 'windows'
        run: |
          CGO_ENABLED=0 GOOS=$os GOARCH=amd64 go build -ldflags="-s -w -trimpath -o LeafSDToolsCompanion.exe main.go
          zip -9q LeafSDTools-Companion-$os-amd64.zip LeafSDToolsCompanion.exe LICENSE
          rm LeafSDToolsCompanion.exe
          printf "sha256: %s\n" "$(shasum -a 256 LeafSDTools-Companion-$os-amd64.zip)"
        env:
          os: ${{ matrix.os }}

      - name: Build [linux]
        if: matrix.os == 'linux'
        run: |
          CGO_ENABLED=0 GOOS=$os GOARCH=amd64 go build -ldflags="-s -w -trimpath -o leafsdtools-companion main.go
          tar -I 'gzip -9' -cf LeafSDTools-Companion-$os-amd64.tar.gz $cli LICENSE
          rm leafsdtools-companion
          printf "sha256: %s\n" "$(shasum -a 256 LeafSDTools-Companion-$os-amd64.tar.gz)"
        env:
          os: ${{ matrix.os }}

      - name: Upload Release Assets [macOS]
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'macOS'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            LeafSDTools-Companion-${{ matrix.os }}-amd64.zip
            LeafSDTools-Companion-${{ matrix.os }}-arm64.zip

      - name: Upload Release Assets [windows]
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LeafSDTools-Companion-${{ matrix.os }}-amd64.zip

      - name: Upload Release Assets [linux]
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LeafSDTools-Companion-${{ matrix.os }}-amd64.tar.gz
